var orderHistory = [
  {
    item: 'book',
    title: 'Javascript for impatient programmers',
    author: 'Rauschmayer, Dr. Axel',
    delivered: 'Aug 8, 2020',
    returnBy:'Sep 7, 2020',
    intialPrice: '31.55',
    totalPrice: '34',
  },
  {
    item: 'Book',
    title: 'The Timeless Way of Building',
    author: 'Alexander, Christopher',
    purchased: 'July 19, 2020',
    delivered: 'July 20, 2020',
    returnBy: 'August 19, 2020',
    intialPrice:'41.33',
    totalPrice: '44.53',
  },
  {
    item: 'Gamecube Controller Adaptor: Super Smash Bros Switch Gamecube Adapter for Wii U, Pc, Support Turbo and Vibration Features. No Driver and No Lag-Gamecube Adapter',
    purchased: 'July 4, 2020',
    delivered: 'July 7, 2020',
    returnBy: 'August 5, 2020',
    intialPrice: '15.98',
    totalPrice: '17.22',
  },
  {
    item: 'Book & Gamecube Controller - Super Smash Bros. Edition (Nintendo Switch)',
    title: 'The Art of Sql',
    author: 'Faroult, Stephan',
    purchased: 'July 3, 2020',
    delivered: 'July 5, 2020',
    returnBy: 'August 4, 2020',
    intialPrice: '33.99 & 94.95',
    totalPrice: '138.93',
  },
];
